services:
  website:
    image: php:apache
    depends_on:
      - api
    ports:
      - "8082:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=${API_USER}
      - PASSWORD=${API_PASSWORD}
      - API_URL=${API_URL}
    networks:
      - api-network

  api:
    image: "ghcr.io/kev-skywalker/learning:v1"
    container_name: api-v1
    ports:
      - "4000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      api-network:
        aliases:
          - ${DOMAIN_NAME}

networks:
  api-network:
    driver: bridge
